// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TM_PE.Data;

#nullable disable

namespace TM_PE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824224038_AddJobTicketSubmissionHistoryActor")]
    partial class AddJobTicketSubmissionHistoryActor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TM_PE.Model.ActivitySubmission", b =>
                {
                    b.Property<int>("SubmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionID"));

                    b.Property<int>("ActivityID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateReviewed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReviewedByEmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubmissionID");

                    b.HasIndex("ActivityID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("ReviewedByEmployeeID");

                    b.ToTable("tbl_activitysubmission");
                });

            modelBuilder.Entity("TM_PE.Model.Criteria", b =>
                {
                    b.Property<int>("CriteriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriteriaId"));

                    b.Property<string>("CriteriaName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("CriteriaId");

                    b.ToTable("tbl_criteria");
                });

            modelBuilder.Entity("TM_PE.Model.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DepartmentId");

                    b.ToTable("tbl_departments");
                });

            modelBuilder.Entity("TM_PE.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("HiredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tbl_employees");
                });

            modelBuilder.Entity("TM_PE.Model.EvaluationResult", b =>
                {
                    b.Property<int>("EvaluationResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationResultID"));

                    b.Property<int>("CriteriaID")
                        .HasColumnType("int");

                    b.Property<int>("EvaluationID")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("StarRating")
                        .HasColumnType("decimal(2,1)");

                    b.HasKey("EvaluationResultID");

                    b.HasIndex("CriteriaID");

                    b.HasIndex("EvaluationID");

                    b.ToTable("tbl_evaluationresult");
                });

            modelBuilder.Entity("TM_PE.Model.Feedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int?>("EvaluationID")
                        .HasColumnType("int");

                    b.Property<string>("FeedbackType")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FeedbackID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("EvaluationID");

                    b.ToTable("tbl_feedback");
                });

            modelBuilder.Entity("TM_PE.Model.FiberPlan", b =>
                {
                    b.Property<int>("FiberPlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FiberPlanID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FiberPlanID");

                    b.HasIndex("PlanName")
                        .IsUnique();

                    b.ToTable("tbl_fiberplan");
                });

            modelBuilder.Entity("TM_PE.Model.JobTicket", b =>
                {
                    b.Property<int>("JobTicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobTicketID"));

                    b.Property<int?>("AssignedByEmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("ClientFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfCompletion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FiberPlan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LocationAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NearestLandmark")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PrimaryNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SecondaryNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("JobTicketID");

                    b.HasIndex("AssignedByEmployeeID");

                    b.ToTable("tbl_jobticket");
                });

            modelBuilder.Entity("TM_PE.Model.JobTicketAssignment", b =>
                {
                    b.Property<int>("JobTicketAssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobTicketAssignmentID"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("bit");

                    b.Property<int>("JobTicketID")
                        .HasColumnType("int");

                    b.HasKey("JobTicketAssignmentID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("JobTicketID");

                    b.ToTable("tbl_jobticketassignment");
                });

            modelBuilder.Entity("TM_PE.Model.JobTicketRescheduleHistory", b =>
                {
                    b.Property<int>("JobTicketRescheduleHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobTicketRescheduleHistoryID"));

                    b.Property<DateTime>("DateChanged")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobTicketID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NewServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OldServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviousRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("JobTicketRescheduleHistoryID");

                    b.HasIndex("JobTicketID");

                    b.ToTable("tbl_jobticketreschedulehistory");
                });

            modelBuilder.Entity("TM_PE.Model.JobTicketSubmission", b =>
                {
                    b.Property<int>("JobTicketSubmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobTicketSubmissionID"));

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobTicketID")
                        .HasColumnType("int");

                    b.Property<int?>("RescheduleHistoryID")
                        .HasColumnType("int");

                    b.Property<int?>("SubmissionHistoryID")
                        .HasColumnType("int");

                    b.HasKey("JobTicketSubmissionID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("JobTicketID");

                    b.HasIndex("RescheduleHistoryID");

                    b.HasIndex("SubmissionHistoryID");

                    b.ToTable("tbl_jobticketsubmission");
                });

            modelBuilder.Entity("TM_PE.Model.JobTicketSubmissionHistory", b =>
                {
                    b.Property<int>("JobTicketSubmissionHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobTicketSubmissionHistoryID"));

                    b.Property<int?>("ActorEmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateChanged")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobTicketID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("JobTicketSubmissionHistoryID");

                    b.HasIndex("ActorEmployeeID");

                    b.HasIndex("JobTicketID");

                    b.ToTable("tbl_jobticketsubmissionhistory");
                });

            modelBuilder.Entity("TM_PE.Model.OfficeTask", b =>
                {
                    b.Property<int>("OfficeTaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficeTaskID"));

                    b.Property<int?>("AssignedByEmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Progress")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TaskNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("OfficeTaskID");

                    b.HasIndex("AssignedByEmployeeID");

                    b.ToTable("tbl_officetask");
                });

            modelBuilder.Entity("TM_PE.Model.PerformanceEvaluation", b =>
                {
                    b.Property<int>("EvaluationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvaluationPeriodMonth")
                        .HasColumnType("int");

                    b.Property<int>("EvaluationPeriodYear")
                        .HasColumnType("int");

                    b.Property<string>("EvaluationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EvaluatorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GeneralFeedback")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OverallRating")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("OverallScore")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("EvaluationID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("tbl_performanceevaluation");
                });

            modelBuilder.Entity("TM_PE.Model.TaskActivity", b =>
                {
                    b.Property<int>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityID"));

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("AssignedEmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedBack")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OfficeTaskID")
                        .HasColumnType("int");

                    b.Property<int>("RejectionCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityID");

                    b.HasIndex("AssignedEmployeeID");

                    b.HasIndex("OfficeTaskID");

                    b.ToTable("tbl_taskactivity");
                });

            modelBuilder.Entity("TM_PE.Model.TaskAssignment", b =>
                {
                    b.Property<int>("TaskAssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskAssignmentID"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("OfficeTaskID")
                        .HasColumnType("int");

                    b.HasKey("TaskAssignmentID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("OfficeTaskID");

                    b.ToTable("tbl_taskassignment");
                });

            modelBuilder.Entity("TM_PE.Model.UserAccount", b =>
                {
                    b.Property<int>("UserAccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAccountID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserAccountID");

                    b.HasIndex("EmployeeID")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("tbl_useraccount");
                });

            modelBuilder.Entity("TM_PE.Model.ActivitySubmission", b =>
                {
                    b.HasOne("TM_PE.Model.TaskActivity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM_PE.Model.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM_PE.Model.Employee", "ReviewedByEmployee")
                        .WithMany()
                        .HasForeignKey("ReviewedByEmployeeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Activity");

                    b.Navigation("Employee");

                    b.Navigation("ReviewedByEmployee");
                });

            modelBuilder.Entity("TM_PE.Model.Employee", b =>
                {
                    b.HasOne("TM_PE.Model.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TM_PE.Model.EvaluationResult", b =>
                {
                    b.HasOne("TM_PE.Model.Criteria", "Criteria")
                        .WithMany()
                        .HasForeignKey("CriteriaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TM_PE.Model.PerformanceEvaluation", "PerformanceEvaluation")
                        .WithMany("Results")
                        .HasForeignKey("EvaluationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criteria");

                    b.Navigation("PerformanceEvaluation");
                });

            modelBuilder.Entity("TM_PE.Model.Feedback", b =>
                {
                    b.HasOne("TM_PE.Model.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TM_PE.Model.PerformanceEvaluation", "Evaluation")
                        .WithMany()
                        .HasForeignKey("EvaluationID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("TM_PE.Model.JobTicket", b =>
                {
                    b.HasOne("TM_PE.Model.Employee", "AssignedByEmployee")
                        .WithMany()
                        .HasForeignKey("AssignedByEmployeeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedByEmployee");
                });

            modelBuilder.Entity("TM_PE.Model.JobTicketAssignment", b =>
                {
                    b.HasOne("TM_PE.Model.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM_PE.Model.JobTicket", "JobTicket")
                        .WithMany("Assignments")
                        .HasForeignKey("JobTicketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("JobTicket");
                });

            modelBuilder.Entity("TM_PE.Model.JobTicketRescheduleHistory", b =>
                {
                    b.HasOne("TM_PE.Model.JobTicket", "JobTicket")
                        .WithMany("RescheduleHistory")
                        .HasForeignKey("JobTicketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobTicket");
                });

            modelBuilder.Entity("TM_PE.Model.JobTicketSubmission", b =>
                {
                    b.HasOne("TM_PE.Model.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM_PE.Model.JobTicket", "JobTicket")
                        .WithMany("Submissions")
                        .HasForeignKey("JobTicketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM_PE.Model.JobTicketRescheduleHistory", "RescheduleHistory")
                        .WithMany("ArchivedSubmissions")
                        .HasForeignKey("RescheduleHistoryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TM_PE.Model.JobTicketSubmissionHistory", "SubmissionHistory")
                        .WithMany("ArchivedSubmissions")
                        .HasForeignKey("SubmissionHistoryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("JobTicket");

                    b.Navigation("RescheduleHistory");

                    b.Navigation("SubmissionHistory");
                });

            modelBuilder.Entity("TM_PE.Model.JobTicketSubmissionHistory", b =>
                {
                    b.HasOne("TM_PE.Model.Employee", "ActorEmployee")
                        .WithMany()
                        .HasForeignKey("ActorEmployeeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TM_PE.Model.JobTicket", "JobTicket")
                        .WithMany("SubmissionHistory")
                        .HasForeignKey("JobTicketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorEmployee");

                    b.Navigation("JobTicket");
                });

            modelBuilder.Entity("TM_PE.Model.OfficeTask", b =>
                {
                    b.HasOne("TM_PE.Model.Employee", "AssignedByEmployee")
                        .WithMany()
                        .HasForeignKey("AssignedByEmployeeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedByEmployee");
                });

            modelBuilder.Entity("TM_PE.Model.PerformanceEvaluation", b =>
                {
                    b.HasOne("TM_PE.Model.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TM_PE.Model.TaskActivity", b =>
                {
                    b.HasOne("TM_PE.Model.Employee", "AssignedEmployee")
                        .WithMany()
                        .HasForeignKey("AssignedEmployeeID");

                    b.HasOne("TM_PE.Model.OfficeTask", "OfficeTask")
                        .WithMany("Activities")
                        .HasForeignKey("OfficeTaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedEmployee");

                    b.Navigation("OfficeTask");
                });

            modelBuilder.Entity("TM_PE.Model.TaskAssignment", b =>
                {
                    b.HasOne("TM_PE.Model.Employee", "Employee")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM_PE.Model.OfficeTask", "OfficeTask")
                        .WithMany("Assignments")
                        .HasForeignKey("OfficeTaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("OfficeTask");
                });

            modelBuilder.Entity("TM_PE.Model.UserAccount", b =>
                {
                    b.HasOne("TM_PE.Model.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TM_PE.Model.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("TM_PE.Model.Employee", b =>
                {
                    b.Navigation("TaskAssignments");
                });

            modelBuilder.Entity("TM_PE.Model.JobTicket", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("RescheduleHistory");

                    b.Navigation("SubmissionHistory");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("TM_PE.Model.JobTicketRescheduleHistory", b =>
                {
                    b.Navigation("ArchivedSubmissions");
                });

            modelBuilder.Entity("TM_PE.Model.JobTicketSubmissionHistory", b =>
                {
                    b.Navigation("ArchivedSubmissions");
                });

            modelBuilder.Entity("TM_PE.Model.OfficeTask", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("TM_PE.Model.PerformanceEvaluation", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
