using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TM_PE.Data;
using TM_PE.Model;

namespace TM_PE.Pages.Manager.JobTickets
{
    public class CreateModel : PageModel
    {
        private readonly AppDbContext _context;

        public CreateModel(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Model.JobTicket JobTicket { get; set; } = new();

        // Populated via hidden inputs generated by JS as field technicians are added
        [BindProperty]
        public List<int> SelectedEmployeeIds { get; set; } = new();

        // The single employee (must be one of SelectedEmployeeIds) marked as the leader
        [BindProperty]
        public int LeaderEmployeeId { get; set; }

        // Used to populate the "Add Assignees" dropdown — Field Technicians only
        public List<Employee> FieldTechnicianList { get; set; } = new();

        // Full records (id + name) for the technicians already selected, in the
        // order they were added. Used to re-render the "Selected" list and hide
        // them from the dropdown when the page is redisplayed after a validation
        // error — otherwise the assignees the manager already picked would
        // silently disappear (the list only ever lived in the browser's JS state)
        // and the manager would have to re-add everyone from scratch.
        public List<Employee> SelectedEmployees { get; set; } = new();

        // Read-only preview of the ticket number that will be generated on save
        public string NextTicketNumber { get; set; } = string.Empty;

        // The logged-in manager creating this ticket - shown read-only and saved
        // automatically as JobTicket.AssignedByEmployeeID, never chosen from the form.
        public string CurrentManagerName { get; set; } = "Manager";

        // Manager-maintained fiber plan options (see the "Fiber Plans" modal on this
        // page) — loaded fresh from tbl_fiberplan on every GET/failed POST since
        // managers can add/remove entries at any time.
        public List<Model.FiberPlan> FiberPlanOptions { get; set; } = new();

        public string[] JobTypeOptions { get; set; } = JobTypes.Allowed;

        public async Task OnGetAsync()
        {
            // Only technicians who actually have a login can be assigned — a
            // technician with no user account has no way to see or act on the
            // job once assigned.
            FieldTechnicianList = await _context.Employees
                .Where(e => e.IsActive && e.RoleType == RoleType.FieldTechnician
                    && _context.UserAccounts.Any(a => a.EmployeeID == e.EmployeeId))
                .OrderBy(e => e.FullName)
                .ToListAsync();

            FiberPlanOptions = await _context.FiberPlans
                .OrderBy(f => f.FiberPlanID)
                .ToListAsync();

            JobTicket.DateCreated = DateTime.Now;
            JobTicket.ServiceDate = DateTime.Now;
            // Default the deadline two days out rather than same-day, so a
            // fresh ticket doesn't start out already due (or overdue the
            // moment the service date passes) - the manager can still pick
            // an earlier or later date before saving.
            JobTicket.DateOfCompletion = DateTime.Now.AddDays(2);
            NextTicketNumber = await GenerateTicketNumberAsync();
            CurrentManagerName = HttpContext.Session.GetString("AuthEmployeeName") ?? "Manager";
        }

        public async Task<IActionResult> OnPostAsync()
        {
            // Auto-generated / hidden fields shouldn't be required on postback validation
            ModelState.Remove("JobTicket.TicketNumber");
            ModelState.Remove("JobTicket.Status");
            // FiberPlan/Description are conditionally required depending on JobType,
            // so their built-in validation attributes are skipped in favor of manual checks below.
            ModelState.Remove("JobTicket.FiberPlan");
            ModelState.Remove("JobTicket.Description");
            // Client Full Name / Primary / Secondary Number are only collected for
            // non-Maintenance jobs, so their built-in [Required] attributes are skipped
            // in favor of the manual, JobType-aware checks below.
            ModelState.Remove("JobTicket.ClientFullName");
            ModelState.Remove("JobTicket.PrimaryNumber");
            ModelState.Remove("JobTicket.SecondaryNumber");

            SelectedEmployeeIds ??= new();

            if (!JobTypes.Allowed.Contains(JobTicket.JobType))
                ModelState.AddModelError("JobTicket.JobType", "Please select a valid job type.");

            if (JobTicket.ServiceDate.Date < DateTime.Now.Date)
                ModelState.AddModelError("JobTicket.ServiceDate", "Date cannot be set to a previous day.");

            // Not required at the database level (older tickets predate this
            // field), but the manager must set one for every new ticket — it's
            // what drives the automatic Overdue status.
            if (JobTicket.DateOfCompletion == null)
                ModelState.AddModelError("JobTicket.DateOfCompletion", "Please set a date of completion.");
            else if (JobTicket.DateOfCompletion.Value.Date < JobTicket.ServiceDate.Date)
                ModelState.AddModelError("JobTicket.DateOfCompletion", "Date of completion cannot be before the service date.");

            if (JobTicket.JobType == JobTypes.Installation)
            {
                if (string.IsNullOrWhiteSpace(JobTicket.FiberPlan) ||
                    !await _context.FiberPlans.AnyAsync(f => f.PlanName == JobTicket.FiberPlan))
                    ModelState.AddModelError("JobTicket.FiberPlan", "Please select a valid fiber plan.");

                JobTicket.Description = null;
            }
            else if (JobTicket.JobType == JobTypes.Repair || JobTicket.JobType == JobTypes.Maintenance || JobTicket.JobType == JobTypes.Inspection)
            {
                if (string.IsNullOrWhiteSpace(JobTicket.Description))
                    ModelState.AddModelError("JobTicket.Description", "Please provide a description.");

                JobTicket.FiberPlan = null;
            }

            // Maintenance jobs don't collect client contact info — clear whatever was
            // submitted (in case the client tampered with the request) instead of
            // requiring it. Every other job type still requires Client Full Name and
            // Primary Number.
            if (JobTicket.JobType == JobTypes.Maintenance)
            {
                JobTicket.ClientFullName = string.Empty;
                JobTicket.PrimaryNumber = string.Empty;
                JobTicket.SecondaryNumber = null;
            }
            else
            {
                if (string.IsNullOrWhiteSpace(JobTicket.ClientFullName))
                    ModelState.AddModelError("JobTicket.ClientFullName", "Client full name is required.");

                if (string.IsNullOrWhiteSpace(JobTicket.PrimaryNumber))
                    ModelState.AddModelError("JobTicket.PrimaryNumber", "Primary number is required.");
                else if (!System.Text.RegularExpressions.Regex.IsMatch(JobTicket.PrimaryNumber, @"^09\d{9}$"))
                    ModelState.AddModelError("JobTicket.PrimaryNumber", "Enter a valid 11-digit Philippine mobile number (e.g. 09171234567).");

                if (!string.IsNullOrWhiteSpace(JobTicket.SecondaryNumber) &&
                    !System.Text.RegularExpressions.Regex.IsMatch(JobTicket.SecondaryNumber, @"^09\d{9}$"))
                    ModelState.AddModelError("JobTicket.SecondaryNumber", "Enter a valid 11-digit Philippine mobile number (e.g. 09171234567).");
            }

            if (!SelectedEmployeeIds.Any())
                ModelState.AddModelError(string.Empty, "Please assign at least one field technician.");

            if (SelectedEmployeeIds.Any() && LeaderEmployeeId == 0)
                ModelState.AddModelError(string.Empty, "Please choose who will lead this job.");

            if (LeaderEmployeeId != 0 && !SelectedEmployeeIds.Contains(LeaderEmployeeId))
                ModelState.AddModelError(string.Empty, "The leader must be one of the assigned field technicians.");

            // Only active Field Technicians with a user account may be assigned, even if the request was tampered with.
            List<int> validEmployeeIds = new();
            if (SelectedEmployeeIds.Any())
            {
                validEmployeeIds = await _context.Employees
                    .Where(e => e.IsActive && e.RoleType == RoleType.FieldTechnician && SelectedEmployeeIds.Contains(e.EmployeeId)
                        && _context.UserAccounts.Any(a => a.EmployeeID == e.EmployeeId))
                    .Select(e => e.EmployeeId)
                    .ToListAsync();

                if (SelectedEmployeeIds.Except(validEmployeeIds).Any())
                    ModelState.AddModelError(string.Empty, "Job tickets can only be assigned to active Field Technicians who have a user account.");
            }

            if (!ModelState.IsValid)
            {
                FieldTechnicianList = await _context.Employees
                    .Where(e => e.IsActive && e.RoleType == RoleType.FieldTechnician
                        && _context.UserAccounts.Any(a => a.EmployeeID == e.EmployeeId))
                    .OrderBy(e => e.FullName)
                    .ToListAsync();
                FiberPlanOptions = await _context.FiberPlans
                    .OrderBy(f => f.FiberPlanID)
                    .ToListAsync();
                NextTicketNumber = await GenerateTicketNumberAsync();
                CurrentManagerName = HttpContext.Session.GetString("AuthEmployeeName") ?? "Manager";

                // Re-hydrate the previously-selected assignees (in the order they
                // were submitted) so the Create page can restore them instead of
                // showing an empty "Add Assignees" list.
                SelectedEmployees = SelectedEmployeeIds
                    .Select(id => FieldTechnicianList.FirstOrDefault(e => e.EmployeeId == id))
                    .Where(e => e != null)
                    .Select(e => e!)
                    .ToList();

                return Page();
            }

            JobTicket.TicketNumber = await GenerateTicketNumberAsync();
            JobTicket.Status = JobTicketStatuses.Pending;
            JobTicket.AssignedByEmployeeID = HttpContext.Session.GetInt32("AuthEmployeeId");

            _context.JobTickets.Add(JobTicket);
            await _context.SaveChangesAsync(); // generates JobTicket.JobTicketID

            foreach (var employeeId in SelectedEmployeeIds)
            {
                _context.JobTicketAssignments.Add(new JobTicketAssignment
                {
                    JobTicketID = JobTicket.JobTicketID,
                    EmployeeID = employeeId,
                    IsLeader = employeeId == LeaderEmployeeId,
                    AssignedDate = DateTime.Now
                });
            }

            await _context.SaveChangesAsync();

            return RedirectToPage("Index");
        }

        // Adds a new fiber plan to the manager-maintained list (see the "Fiber
        // Plans" modal). Called via AJAX from the Create page; returns JSON
        // rather than redirecting since it doesn't touch the ticket form itself.
        public async Task<IActionResult> OnPostAddFiberPlanAsync(string planName)
        {
            planName = (planName ?? string.Empty).Trim();

            if (string.IsNullOrWhiteSpace(planName))
                return new JsonResult(new { success = false, message = "Please enter a fiber plan." }) { StatusCode = 400 };

            if (planName.Length > Model.FiberPlanRules.MaxLength)
                return new JsonResult(new { success = false, message = $"Fiber plan name is too long (max {Model.FiberPlanRules.MaxLength} characters)." }) { StatusCode = 400 };

            if (!System.Text.RegularExpressions.Regex.IsMatch(planName, Model.FiberPlanRules.AllowedPattern))
                return new JsonResult(new { success = false, message = "Only letters, numbers, spaces, and . , - / ₱ # & ( ) are allowed." }) { StatusCode = 400 };

            if (await _context.FiberPlans.AnyAsync(f => f.PlanName == planName))
                return new JsonResult(new { success = false, message = "That fiber plan already exists." }) { StatusCode = 400 };

            var plan = new Model.FiberPlan { PlanName = planName };
            _context.FiberPlans.Add(plan);
            await _context.SaveChangesAsync();

            return new JsonResult(new { success = true, id = plan.FiberPlanID, name = plan.PlanName });
        }

        // Removes a fiber plan from the manager-maintained list. Tickets that
        // already used this plan keep their FiberPlan text untouched — it's
        // stored directly on the ticket, not as a foreign key.
        public async Task<IActionResult> OnPostDeleteFiberPlanAsync(int id)
        {
            var plan = await _context.FiberPlans.FindAsync(id);
            if (plan == null)
                return new JsonResult(new { success = false, message = "Fiber plan not found." }) { StatusCode = 404 };

            _context.FiberPlans.Remove(plan);
            await _context.SaveChangesAsync();

            return new JsonResult(new { success = true });
        }

        private async Task<string> GenerateTicketNumberAsync()
        {
            var count = await _context.JobTickets.CountAsync();
            return $"JOB-{DateTime.Now:yyyy}-{(count + 1):D4}";
        }
    }
}
