using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TM_PE.Data;
using TM_PE.Model;

namespace TM_PE.Pages.Manager.OfficeTask
{
    public class CreateModel : PageModel
    {
        // TODO: replace ApplicationDbContext with your actual DbContext class name if different
        private readonly AppDbContext _context;

        public CreateModel(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Model.OfficeTask OfficeTask { get; set; } = new();

        // Populated via hidden inputs generated by JS as employees are added
        [BindProperty]
        public List<int> SelectedEmployeeIds { get; set; } = new();

        // Populated via hidden inputs generated by JS as activities are added
        [BindProperty]
        public List<string> Activities { get; set; } = new();

        // Used to populate the "Assign Employees" dropdown
        public List<Employee> EmployeeList { get; set; } = new();

        // Read-only preview of the task number that will be generated on save
        public string NextTaskNumber { get; set; } = string.Empty;

        // The logged-in manager creating this task - shown read-only and saved
        // automatically as OfficeTask.AssignedByEmployeeID, never chosen from the form.
        public string CurrentManagerName { get; set; } = "Manager";

        public async Task OnGetAsync()
        {
            // Only active Office Staff who actually have a login can be assigned —
            // a staff member with no user account has no way to see or act on the
            // task once assigned.
            EmployeeList = await _context.Employees
                .Where(e => e.IsActive && e.RoleType == RoleType.OfficeStaff
                    && _context.UserAccounts.Any(a => a.EmployeeID == e.EmployeeId))
                .OrderBy(e => e.FullName) // adjust to match your Employee model's name property
                .ToListAsync();

            OfficeTask.DateCreated = DateTime.Now;
            // Default the due date two days out rather than same-day as
            // DateCreated, so a fresh task doesn't start out already due -
            // the manager can still pick an earlier or later date before saving.
            OfficeTask.DueDate = DateTime.Now.AddDays(2);
            NextTaskNumber = await GenerateTaskNumberAsync();
            CurrentManagerName = HttpContext.Session.GetString("AuthEmployeeName") ?? "Manager";
        }

        public async Task<IActionResult> OnPostAsync()
        {
            // TaskNumber is auto-generated server-side, so don't require it on post
            ModelState.Remove("OfficeTask.TaskNumber");

            SelectedEmployeeIds ??= new();
            Activities ??= new();

            // Due date can't be set in the past
            if (OfficeTask.DueDate.Date < DateTime.Now.Date)
                ModelState.AddModelError("OfficeTask.DueDate", "Due date cannot be set to a previous day.");

            if (!SelectedEmployeeIds.Any())
                ModelState.AddModelError(string.Empty, "Please assign at least one employee.");

            if (!Activities.Any())
                ModelState.AddModelError(string.Empty, "Please add at least one activity.");

            // Only active Office Staff with a user account may be assigned, even if the request was tampered with.
            if (SelectedEmployeeIds.Any())
            {
                var validEmployeeIds = await _context.Employees
                    .Where(e => e.IsActive && e.RoleType == RoleType.OfficeStaff && SelectedEmployeeIds.Contains(e.EmployeeId)
                        && _context.UserAccounts.Any(a => a.EmployeeID == e.EmployeeId))
                    .Select(e => e.EmployeeId)
                    .ToListAsync();

                if (SelectedEmployeeIds.Except(validEmployeeIds).Any())
                    ModelState.AddModelError(string.Empty, "Tasks can only be assigned to active Office Staff employees who have a user account.");
            }

            if (!ModelState.IsValid)
            {
                EmployeeList = await _context.Employees
                    .Where(e => e.IsActive && e.RoleType == RoleType.OfficeStaff
                        && _context.UserAccounts.Any(a => a.EmployeeID == e.EmployeeId))
                    .OrderBy(e => e.FullName)
                    .ToListAsync();
                NextTaskNumber = await GenerateTaskNumberAsync();
                CurrentManagerName = HttpContext.Session.GetString("AuthEmployeeName") ?? "Manager";
                return Page();
            }

            OfficeTask.TaskNumber = await GenerateTaskNumberAsync();
            OfficeTask.Status = "Pending";
            OfficeTask.Progress = 0;
            OfficeTask.AssignedByEmployeeID = HttpContext.Session.GetInt32("AuthEmployeeId");

            _context.OfficeTasks.Add(OfficeTask);
            await _context.SaveChangesAsync(); // generates OfficeTask.OfficeTaskID

            foreach (var employeeId in SelectedEmployeeIds)
            {
                _context.TaskAssignments.Add(new TaskAssignment
                {
                    OfficeTaskID = OfficeTask.OfficeTaskID,
                    EmployeeID = employeeId,
                    AssignedDate = DateTime.Now
                });
            }

            // Activities are no longer pre-assigned to a specific employee here.
            // - If exactly one employee is on the task, every activity is implicitly theirs.
            // - If more than one employee is on the task, activities start unclaimed;
            //   whoever uploads a submission first claims that activity (see OfficeStaff Details page).
            int? autoAssigneeId = SelectedEmployeeIds.Count == 1 ? SelectedEmployeeIds[0] : (int?)null;

            foreach (var activityName in Activities)
            {
                _context.TaskActivities.Add(new TaskActivity
                {
                    OfficeTaskID = OfficeTask.OfficeTaskID,
                    ActivityName = activityName,
                    AssignedEmployeeID = autoAssigneeId,
                    Status = "Pending",
                    DateCreated = DateTime.Now
                });
            }

            await _context.SaveChangesAsync();

            return RedirectToPage("Index");
        }

        private async Task<string> GenerateTaskNumberAsync()
        {
            var count = await _context.OfficeTasks.CountAsync();
            return $"TASK-{DateTime.Now:yyyy}-{(count + 1):D4}";
        }
    }
}
