using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using TM_PE.Data;
using TM_PE.Model;

namespace TM_PE.Pages.Manager.OfficeTask
{
    public class EditModel : PageModel
    {
        private readonly AppDbContext _context;

        public EditModel(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Model.OfficeTask OfficeTask { get; set; } = default!;

        // Final list of employee IDs that should remain assigned after save.
        // Populated via hidden inputs generated by JS (pre-filled with current assignees).
        [BindProperty]
        public List<int> SelectedEmployeeIds { get; set; } = new();

        // ActivityIDs of existing activities the user did NOT remove.
        [BindProperty]
        public List<int> KeptActivityIds { get; set; } = new();

        // Newly typed activity names to add on this edit.
        [BindProperty]
        public List<string> NewActivities { get; set; } = new();

        // Used to populate the "Assign Employees" dropdown
        public List<Employee> EmployeeList { get; set; } = new();

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var officeTask = await _context.OfficeTasks
                .Include(t => t.Assignments)
                    .ThenInclude(a => a.Employee)
                .Include(t => t.Activities).ThenInclude(a => a.AssignedEmployee)
                .Include(t => t.AssignedByEmployee)
                .FirstOrDefaultAsync(m => m.OfficeTaskID == id);

            if (officeTask == null)
            {
                return NotFound();
            }

            // Completed tasks (every activity Approved) are locked — no further edits allowed.
            if (officeTask.Status == "Completed")
            {
                return RedirectToPage("Details", new { id });
            }

            OfficeTask = officeTask;

            EmployeeList = await _context.Employees
                .OrderBy(e => e.FullName)
                .ToListAsync();

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            // TaskNumber is auto-generated and shown disabled, so don't require it on post
            ModelState.Remove("OfficeTask.TaskNumber");
            ModelState.Remove("OfficeTask.Assignments");
            ModelState.Remove("OfficeTask.Activities");

            SelectedEmployeeIds ??= new();
            KeptActivityIds ??= new();
            NewActivities ??= new();
            NewActivities = NewActivities.Where(a => !string.IsNullOrWhiteSpace(a)).ToList();

            if (!SelectedEmployeeIds.Any())
                ModelState.AddModelError(string.Empty, "Please assign at least one employee.");

            if (!KeptActivityIds.Any() && !NewActivities.Any())
                ModelState.AddModelError(string.Empty, "Please keep or add at least one activity.");

            if (!ModelState.IsValid)
            {
                EmployeeList = await _context.Employees
                    .OrderBy(e => e.FullName)
                    .ToListAsync();

                // Reload navigation collections so the form can re-render with the right badges/list
                var reload = await _context.OfficeTasks
                    .Include(t => t.Assignments).ThenInclude(a => a.Employee)
                    .Include(t => t.Activities).ThenInclude(a => a.AssignedEmployee)
                    .Include(t => t.AssignedByEmployee)
                    .AsNoTracking()
                    .FirstOrDefaultAsync(t => t.OfficeTaskID == OfficeTask.OfficeTaskID);

                if (reload != null)
                {
                    OfficeTask.Assignments = reload.Assignments;
                    OfficeTask.Activities = reload.Activities;
                    OfficeTask.AssignedByEmployee = reload.AssignedByEmployee;
                }

                return Page();
            }

            var task = await _context.OfficeTasks
                .Include(t => t.Assignments)
                .Include(t => t.Activities).ThenInclude(a => a.AssignedEmployee)
                .FirstOrDefaultAsync(t => t.OfficeTaskID == OfficeTask.OfficeTaskID);

            if (task == null)
            {
                return NotFound();
            }

            // Completed tasks are locked — no further edits allowed, even if this
            // page was submitted directly.
            if (task.Status == "Completed")
            {
                return RedirectToPage("Details", new { id = task.OfficeTaskID });
            }

            // Update core fields (TaskNumber intentionally left untouched)
            // NOTE: Status and Progress are intentionally NOT taken from the posted
            // OfficeTask model here. Those inputs are commented out in Edit.cshtml,
            // so OfficeTask.Status/Progress always arrive as null/0 on postback.
            // They are recalculated below from the activities instead.
            task.TaskName = OfficeTask.TaskName;
            task.Description = OfficeTask.Description;
            task.DueDate = OfficeTask.DueDate;

            // --- Sync employee assignments ---
            var currentEmployeeIds = task.Assignments.Select(a => a.EmployeeID).ToList();

            var employeesToRemove = task.Assignments
                .Where(a => !SelectedEmployeeIds.Contains(a.EmployeeID))
                .ToList();
            foreach (var a in employeesToRemove)
                _context.TaskAssignments.Remove(a);

            var employeeIdsToAdd = SelectedEmployeeIds.Except(currentEmployeeIds);
            foreach (var employeeId in employeeIdsToAdd)
            {
                _context.TaskAssignments.Add(new TaskAssignment
                {
                    OfficeTaskID = task.OfficeTaskID,
                    EmployeeID = employeeId,
                    AssignedDate = DateTime.Now
                });
            }

            // --- Sync activities ---
            var activitiesToRemove = task.Activities
                .Where(a => !KeptActivityIds.Contains(a.ActivityID))
                .ToList();
            foreach (var a in activitiesToRemove)
                _context.TaskActivities.Remove(a);

            // Activities are no longer manually assigned to a specific employee.
            // - Exactly one employee left on the task -> every activity (existing and new) is implicitly theirs.
            // - More than one employee -> activities are unclaimed until someone uploads a submission for them.
            int? autoAssigneeId = SelectedEmployeeIds.Count == 1 ? SelectedEmployeeIds[0] : (int?)null;

            foreach (var activity in task.Activities.Where(a => KeptActivityIds.Contains(a.ActivityID)))
            {
                // Don't touch activities someone has already claimed by uploading a submission,
                // and never touch an already-Approved activity.
                if (activity.Status == "Approved")
                    continue;

                if (SelectedEmployeeIds.Count == 1)
                {
                    activity.AssignedEmployeeID = autoAssigneeId;
                }
                else if (activity.AssignedEmployeeID.HasValue && !SelectedEmployeeIds.Contains(activity.AssignedEmployeeID.Value))
                {
                    // The employee who had claimed this activity was removed from the task; reopen it.
                    activity.AssignedEmployeeID = null;
                }
            }

            foreach (var activityName in NewActivities)
            {
                _context.TaskActivities.Add(new TaskActivity
                {
                    OfficeTaskID = task.OfficeTaskID,
                    ActivityName = activityName,
                    AssignedEmployeeID = autoAssigneeId,
                    Status = "Pending",
                    DateCreated = DateTime.Now
                });
            }

            await _context.SaveChangesAsync();

            await RecalculateTaskAsync(task.OfficeTaskID);

            return RedirectToPage("Index");
        }

        // ---------------------------------------------------------------
        // Status/Progress auto-calculation (mirrors Details page logic)
        // ---------------------------------------------------------------
        // Rule: Progress = % of activities that are Approved.
        //       Status = Completed   -> every activity is Approved
        //                In Progress -> at least one activity is Approved or Submitted
        //                Pending     -> otherwise (or no activities yet)
        private async Task RecalculateTaskAsync(int officeTaskId)
        {
            var task = await _context.OfficeTasks
                .Include(t => t.Activities).ThenInclude(a => a.AssignedEmployee)
                .FirstOrDefaultAsync(t => t.OfficeTaskID == officeTaskId);

            if (task == null)
            {
                return;
            }

            var activities = task.Activities.ToList();

            if (activities.Count == 0)
            {
                task.Status = "Pending";
                task.Progress = 0;
                task.Score = 0;
            }
            else
            {
                int approvedCount = activities.Count(a => a.Status == "Approved");
                task.Progress = Math.Round((decimal)approvedCount / activities.Count * 100, 0);

                decimal pointsPerActivity = 100m / activities.Count;
                task.Score = Math.Round(pointsPerActivity * approvedCount, 2);

                if (approvedCount == activities.Count)
                {
                    if (task.Status != "Completed") task.DateCompleted = DateTime.Now;
                    task.Status = "Completed";
                }
                else if (activities.Any(a => a.Status == "Approved" || a.Status == "Submitted"))
                {
                    task.Status = "In Progress";
                }
                else if (task.Status != "In Progress")
                {
                    // Once a task has been marked In Progress, it stays there even if
                    // rejecting the only Submitted/Approved activity leaves nothing
                    // currently qualifying - it should never fall back to Pending.
                    task.Status = "Pending";
                }
            }

            // A task that isn't finished and is past its due date is Overdue, regardless of
            // the status computed above.
            if (task.Status != "Completed" && task.DueDate.Date < DateTime.Now.Date)
            {
                task.Status = "Overdue";
            }

            await _context.SaveChangesAsync();
        }
    }
}